config/routes.rb
Rails.application.routes.draw do

  scope "(:locale)", locale: /en|de/ do
    get '/:locale' => 'home#index'
    root 'home#index'
    get 'users/sign_up', to: redirect('') unless BP_CONFIG['registration_is_enabled']

    devise_for :users

    resources :articles
    resources :projects

    get 'home' => 'home#index'
    get 'about' => 'about#show'

  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  resourcify

  belongs_to :author, :class_name => 'User', :foreign_key => :author_id

  translates :title, :content, :fallbacks_for_empty_translations => true

  default_scope { order('created_at DESC') }

  self.per_page = BP_CONFIG['articles_per_page']

  def content_preview
    content.truncate(BP_CONFIG['article_preview_sign_length']).bbcode_to_html_with_formatting unless content.nil?
  end

  def content_with_bbcode_and_formatting
    content.bbcode_to_html_with_formatting unless content.nil?
  end

  def self.latest_articles
    limit(BP_CONFIG['count_of_articles_on_index_page'])
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  resourcify
  translates :description, :fallbacks_for_empty_translations => true

  def description_preview
    description.truncate(BP_CONFIG['project_preview_sign_length']).bbcode_to_html_with_formatting unless description.nil?
  end

  def description_with_bbcode_and_formatting
    description.bbcode_to_html_with_formatting unless description.nil?
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :articles
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def show
		@admins = User.with_role(:admin).order('name ASC')
    @mods = User.with_role(:moderator).order('name ASC')
    @team = User.with_role(:developer).order('name ASC')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :set_locale

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password) }
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

  def set_locale
    I18n.locale = params[:locale] || get_locale_from_domain || I18n.default_locale
  end

  def get_locale_from_domain
    locale = BP_CONFIG['localized_domains'][request.host] || ""
    I18n.available_locales.include?(locale.to_sym) ? locale : nil
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  respond_to :html

  def index
    @articles = Article.page(params[:page])
    respond_with(@articles)
  end

  def show
    respond_with(@article)
  end

  def new
    @article = Article.new

    respond_with(@article)
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.author = current_user
    @article.save
    respond_with(@article)
  end

  def update
    @article.update(article_params)
    respond_with(@article)
  end

  def destroy
    @article.destroy
    respond_with(@article)
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  respond_to :html

  def index
    @projects = Project.all
    respond_with(@projects)
  end

  def show
    respond_with(@project)
  end

  def new
    @project = Project.new
    respond_with(@project)
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.save
    respond_with(@project)
  end

  def update
    @project.update(project_params)
    respond_with(@project)
  end

  def destroy
    @project.destroy
    respond_with(@project)
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :description, :description_de, :link)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user_is_admin?
    user_signed_in? && (current_user.has_role? :admin)
  end

  def current_user_is_mod?
    user_signed_in? && (current_user.has_role? :moderator)
  end

  def current_user_is_mod_or_admin?
    current_user_is_mod? || current_user_is_admin?
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def editedHelper(article)
    t('.edited') + l(article.updated_at) if !article.nil? && !(article.updated_at.eql? article.created_at)
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/about/show.html.erb
<div class="page-header">
  <h1><%=t '.title', :default => 'About' %></h1>
</div>

<h3><%=t '.who_heading', :default => 'Who are we?' %></h3>
<p><%=t '.who_content', :default => '' %></p>

<h3><%=t '.what_heading', :default => 'What do we want?' %></h3>
<p><%=t '.what_content', :default => '' %></p>

<h3><%=t '.bp_heading', :default => 'What is BluePanel?' %></h3>
<p><%=t '.bp_content', :default => '' %></p>

<h2><%=t '.contact', :default => 'Contact' %></h2>
<p>Mail: info[AT]bluepanel[DOT]org</p>
<p>IRC: <%= link_to '#bluepanel', 'irc://irc.freenode.net/#bluepanel' %></p>

<div class="adminList">
  <h3><%=t '.admins', :default => 'Administrators' %></h3>
  <% @admins.each do |admin| %>
      <div class="admin">
        <%= admin.name %>
      </div>
  <% end %>
</div>

<div class="modList">
  <h3><%=t '.global_mods', :default => 'Global Moderators' %></h3>
  <% @mods.each do |mod| %>
      <div class="mod">
        <%= mod.name %>
      </div>
  <% end %>
</div>

<div class="developerList">
  <h3><%=t '.developers', :default => 'Developers' %></h3>
  <% @team.each do |member| %>
    <div class="developer">
      <%= member.name %>
    </div>
  <% end %>
</div>

app/views/articles/_article.html.erb
<article>
  <header>
    <h1><%= link_to article.title, article_path(article) %></h1>
    <div class="articleInfo" >
      <span class="articleAuthor" ><%= article.author.name %></span>
      <span class="articleDate" ><%=l article.created_at %></span>
    </div>
  </header>
  <div class="articleBody">
    <%= (defined?(locals) && locals[:preview]) ? raw(article.content_preview) : raw(article.content_with_bbcode_and_formatting) %>
  </div>
  <footer class="articleBottomMargin">
    <p class="editedArticle">
      <%= editedHelper(article) %>
    </p>
    <% if can? (:edit || :destroy), article %>
      <div class="articleButtons">
        <% if can? :edit, article %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_article_path(article), :class => 'btn btn-default btn-xs' %>
        <% end %>
        <% if can? :destroy, article %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      article_path(article),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        <% end %>
      </div>
    <% end %>
  </footer>
</article>

app/views/articles/_form.html.erb
<%= form_for @article, :html => { :class => "form-horizontal article" } do |f| %>

    <% if @article.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%
            if @article.errors.count == 1
              puts t('.errors.one');
            else
              puts t('.errors.other', count: @article.errors.count);
            end
          %>
        </h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :title, t('.title'), :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%= error_span(@article[:title]) %>
  </div>
  <div class="control-group">
    <%= f.label :content, t('.content'), :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :content, :class => 'form-control' %>
    </div>
    <%= error_span(@article[:content]) %>
  </div>


  <%= f.submit t('.create'), :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            articles_path, :class => 'btn btn-default' %>

<% end %>

app/views/articles/edit.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/index.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>

<section>
  <% if @articles.exists? %>
    <%= render @articles.first %>
    <%= render @articles[1..-1], :locals => { :preview => true } %>
  <% end %>
</section>

<% if can? :create, Article %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_article_path,
              :class => 'btn btn-primary' %>
<% end %>

<%= will_paginate @articles, renderer: BootstrapPagination::Rails %>

app/views/articles/new.html.erb
<%- model_class = Article -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/articles/show.html.erb
<%- model_class = Article -%>
<article>
  <header class="page-header">
    <h1><%= @article.title %></h1>
    <div class="articleInfoSingle" > <span class="articleAuthor" ><%= @article.author.name %></span> <span class="articleDate" ><%=l @article.created_at %></span> </div>
  </header>
  <div class="articleBody">
    <%= raw @article.content_with_bbcode_and_formatting %>
  </div>
  <footer class="articleBottomMargin">
    <p class="editedArticle">
      <%= editedHelper(@article) %>
    </p>
    <div class="articleButtons">
      <%= link_to t('.back', :default => t("helpers.links.back")),
                  articles_path, :class => 'btn btn-default'  %>
      <% if can? :edit, @article %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_article_path(@article), :class => 'btn btn-default' %>
      <% end %>
      <% if can? :destroy, @article %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    article_path(@article),
                    :method => 'delete',
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-danger' %>
      <% end %>
    </div>
  </footer>
</article>

app/views/home/index.html.erb
<%= render Article.latest_articles, :locals => { :preview => true } %>

app/views/layouts/_navigation.html.erb
<%= nav_bar :responsive => true, :brand => image_tag('bluepanel-small-logo-light-e.png') do %>
  <%= menu_group do %>
    <%= menu_item t('navigation.main.home'), home_path %>
    <%= menu_item t('navigation.main.articles'), articles_path %>
    <%= menu_item t('navigation.main.projects'), projects_path %>
    <%= menu_item t('navigation.main.about'), about_path %>
  <% end %>
  <%= menu_group :pull => :right do %>
    <% if user_signed_in? %>
      <%= menu_item t('navigation.user.edit_profile'), edit_user_registration_path %>
      <%= menu_item t('navigation.user.sign_out'), destroy_user_session_path, :method => :delete %>
    <% else %>
      <%= menu_item t('navigation.user.sign_up'), new_user_registration_path if BP_CONFIG['registration_is_enabled'] %>
      <%= menu_item t('navigation.user.sign_in'), new_user_session_path %>
    <% end %>

    <li class="dropdown">
      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
        <%= image_tag('globe_16.png') %> | <%= I18n.locale %> <b class="caret"></b>
      </a>
      <ul class="dropdown-menu">
        <li><%= link_to "en", params.merge(locale: :en) %></li>
        <li><%= link_to "de", params.merge(locale: :de) %></li>
      </ul>
    </li>

  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BluePanel - Source that matters…</title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= piwik_tracking_tag %>
</head>
<body>

<%= render 'layouts/navigation' %>

<div class="container">

  <%= bootstrap_flash %>

  <%= yield %>
</div>
<footer class="pageFooter">
</footer>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project, :html => { :class => "form-horizontal project" } do |f| %>

    <% if @project.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title">
          <%
            if @project.errors.count == 1
              puts t('.errors.one');
            else
              puts t('.errors.other', count: @project.errors.count);
            end 
          %>  
        </h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @project.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, t('.name'), :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@project[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, t('.description'), :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <%= error_span(@project[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :link, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :link, :class => 'form-control' %>
    </div>
    <%= error_span(@project[:link]) %>
  </div>


  <%= f.submit t('.create'), :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            projects_path, :class => 'btn btn-default' %>

<% end %>

app/views/projects/edit.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/index.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%=t '.name', :default => model_class.human_attribute_name(:name) %></th>
      <th><%=t '.description', :default => model_class.human_attribute_name(:description) %></th>
      <th><%=t '.link', :default => model_class.human_attribute_name(:link) %></th>
      <% if can? (:edit || :destroy), Project %>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      <% end %>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project_path(project) %></td>
        <td><%= raw project.description_preview %></td>
        <td><%= link_to t('.on_github', :default => 'View on GitHub'), project.link, class: 'btn btn-primary btn-xs' %></td>
        <% if can? (:edit || :destroy), project %>
          <td>
            <% if can? :edit, project %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                          edit_project_path(project), :class => 'btn btn-default btn-xs' %>
            <% end %>
            <% if can? :destroy, project %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          project_path(project),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-xs btn-danger' %>
            <% end %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, Project %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_project_path,
              :class => 'btn btn-primary' %>
<% end %>

app/views/projects/new.html.erb
<%- model_class = Project -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/projects/show.html.erb
<%- model_class = Project -%>
<article>
  <header class="page-header">
    <h1><%= @project.name %></h1>
  </header>

  <div class="project-section">
    <p><%= raw @project.description_with_bbcode_and_formatting %></p>
  </div>
  <footer>
    <p><%= link_to t('.on_github', :default => 'Project on Github'), @project.link, class: 'btn btn-primary btn-xs' %></p>
    <%= link_to t('.back', :default => t("helpers.links.back")),
                  projects_path, :class => 'btn btn-default'  %>
    <% if can? :edit, @project %>
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_project_path(@project), :class => 'btn btn-default' %>
    <% end %>
    <% if can? :destroy, @project %>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    project_path(@project),
                    :method => 'delete',
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn btn-danger' %>
    <% end %>
  </footer>
</article>